import os
import shutil
import subprocess
from config import TEMP_DIR


def prepare_flutter_project(code: str, app_name: str, project_dir: str) -> bool:
    """Flutter loyiha strukturasini yaratadi"""
    try:
        # lib/main.dart yaratish
        lib_dir = os.path.join(project_dir, "lib")
        os.makedirs(lib_dir, exist_ok=True)
        
        with open(os.path.join(lib_dir, "main.dart"), "w", encoding="utf-8") as f:
            f.write(code)
        
        # pubspec.yaml yaratish
        safe_name = app_name.lower().replace(" ", "_").replace("-", "_")
        pubspec = f"""name: {safe_name}
description: Generated by TelegramBuilderBot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
"""
        with open(os.path.join(project_dir, "pubspec.yaml"), "w", encoding="utf-8") as f:
            f.write(pubspec)
        
        return True
    except Exception as e:
        print(f"Flutter project prepare error: {e}")
        return False


def add_logo_to_flutter(logo_path: str, project_dir: str):
    """Logo rasmni Flutter loyihasiga qo'shadi"""
    try:
        assets_dir = os.path.join(project_dir, "assets")
        os.makedirs(assets_dir, exist_ok=True)
        
        # Logoni nusxalash
        dest = os.path.join(assets_dir, "logo.png")
        shutil.copy2(logo_path, dest)
        
        # pubspec.yaml ga assets qo'shish
        pubspec_path = os.path.join(project_dir, "pubspec.yaml")
        with open(pubspec_path, "r") as f:
            content = f.read()
        
        if "assets:" not in content:
            content += "\n  assets:\n    - assets/logo.png\n"
            with open(pubspec_path, "w") as f:
                f.write(content)
    except Exception as e:
        print(f"Logo add error: {e}")


def build_apk(project_dir: str, app_name: str) -> tuple[bool, str]:
    """
    Flutter APK yaratadi.
    Qaytaradi: (muvaffaqiyatli, apk_yoli_yoki_xato)
    """
    try:
        # Flutter mavjudligini tekshirish
        flutter_check = subprocess.run(
            ["flutter", "--version"],
            capture_output=True, text=True, timeout=30
        )
        
        if flutter_check.returncode != 0:
            return False, "flutter_not_installed"
        
        # flutter pub get
        pub_result = subprocess.run(
            ["flutter", "pub", "get"],
            capture_output=True, text=True,
            cwd=project_dir, timeout=120
        )
        
        if pub_result.returncode != 0:
            return False, f"Kutubxonalar yuklanmadi:\n{pub_result.stderr[:500]}"
        
        # APK build
        build_result = subprocess.run(
            ["flutter", "build", "apk", "--release", "--no-tree-shake-icons"],
            capture_output=True, text=True,
            cwd=project_dir, timeout=600
        )
        
        if build_result.returncode != 0:
            return False, f"Build xatosi:\n{build_result.stderr[:500]}"
        
        # APK faylni topish
        apk_path = os.path.join(project_dir, "build", "app", "outputs", 
                                "flutter-apk", "app-release.apk")
        
        if os.path.exists(apk_path):
            return True, apk_path
        else:
            return False, "APK fayl topilmadi"
            
    except FileNotFoundError:
        return False, "flutter_not_installed"
    except subprocess.TimeoutExpired:
        return False, "Build jarayoni juda uzoq davom etdi (timeout)"
    except Exception as e:
        return False, str(e)


def is_flutter_available() -> bool:
    """Flutter o'rnatilganmi tekshiradi"""
    try:
        result = subprocess.run(
            ["flutter", "--version"],
            capture_output=True, timeout=10
        )
        return result.returncode == 0
    except:
        return False
